{{- if and .Values.integrationTests.enabled .Values.integrationTests.atpStorage.bucket }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "consul-integration-tests.name" . }}-atp-storage-secret
  labels:
    {{- include "consul-service.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "consul-integration-tests.name" . }}
type: Opaque
data:
  username: {{ .Values.integrationTests.atpStorage.username | b64enc | quote }}
  password: {{ .Values.integrationTests.atpStorage.password | b64enc | quote }}
{{- end }}

